api:
  build: .
  environment:
    - PYTHONPATH=.
  command: python -u main.py
  ports:
    - "5000:5000"
  volumes:
    - ./src:/stay-safe
  links:
    - db
  restart: on-failure
  stdin_open: true
  tty: true
  environment:
    - PYTHONPATH=.
db:
  image: mongo:3.0.2
crawler_crimes:
  build: .
  volumes:
    - ./src/crawlers/crimes:/stay-safe
  links:
    - db
    - selenium
  stdin_open: true
  tty: true
selenium:
  image: selenium/standalone-firefox
  ports:
    - "4444:4444"
