name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run build
        run: |
          docker-compose --file docker-compose.yml build
          
      - name: Analysing the code with pylint
        run: |
          docker-compose run api sh -c "pylint --fail-under=8 **/*.py"
          
      - name: Run tests
        run: |
          docker-compose --file docker-compose.yml run api coverage run -m pytest
          
      - name: ls
        run: |
          docker-compose --file docker-compose.yml run api coverage json -o ${{github.workspace}}/coverage.json
          ls
      
      - name: Publish code coverage
        run: |
          docker-compose --file docker-compose.yml run api codeclimate-test-reporter --token ${{secrets.CC_TEST_REPORTER_ID}}
        #env:
        #  CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        #with:
        #  coverageCommand: docker-compose --file docker-compose.yml run api coverage json
        #  coverageLocations: ${{github.workspace}}/coverage.json:coverage.py
  
